providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn src.app:app --host 0.0.0.0 --port $PORT"

