services:
  - type: web
    name: vloghub-backend
    env: python
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --app-dir backend
    envVars:
      - key: PORT
        sync: false
      - key: PYTHON_VERSION
        value: 3.11

