services:
  - type: web
    name: YoutubeScriptDemo
    env: python
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        sync: false
      - key: PYTHON_VERSION
        value: 3.11

